// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqixzpxjqizzjazgarbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaXh6cHhqcWl6emphemdhcmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTM4NTksImV4cCI6MjA3MjcyOTg1OX0.YN8m2vjScRPM7yJXvLv8jPfFQHRDPdcXBtuLys0dw7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});